name: Bump version and release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Яку частину версії підняти?"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "last_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          last=${{ steps.get_tag.outputs.last_tag }}
          bump=${{ github.event.inputs.bump }}

          # Прибираємо "v"
          ver=${last#v}
          major=$(echo $ver | cut -d. -f1)
          minor=$(echo $ver | cut -d. -f2)
          patch=$(echo $ver | cut -d. -f3)

          case $bump in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
          esac

          new="v$major.$minor.$patch"
          echo "new_tag=$new" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Build module archive
        run: |
          mkdir -p dist
          VERSION=${{ steps.bump.outputs.new_tag }}
          cd ./Okay/Modules/Sviat
          zip -r "../../../../dist/BlackBox-${VERSION}.zip" BlackBox

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
          files: dist/BlackBox-${{ steps.bump.outputs.new_tag }}.zip
