name: Bump version and release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Яку частину версії підняти?"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          last_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "last_tag=$last_tag" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          last=${{ steps.get_tag.outputs.last_tag }}
          bump=${{ github.event.inputs.bump }}

          ver=${last#v}
          major=$(echo $ver | cut -d. -f1)
          minor=$(echo $ver | cut -d. -f2)
          patch=$(echo $ver | cut -d. -f3)

          case $bump in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
          esac

          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEW_TAG=${{ steps.bump.outputs.new_tag }}
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
            echo "Tag $NEW_TAG already exists. Deleting it."
            git tag -d "$NEW_TAG"
            git push origin --delete "$NEW_TAG" || true
          fi
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Build module archive
        run: |
          VERSION=${{ steps.bump.outputs.new_tag }}
          mkdir -p dist
          zip -r dist/BlackBox-${VERSION}.zip Okay/Modules/Sviat/BlackBox

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Release ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
          files: dist/BlackBox-${{ steps.bump.outputs.new_tag }}.zip
          fail_on_unmatched_files: false
          draft: false
          prerelease: false